import axios, { AxiosError } from 'axios';
import { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import React, { useEffect, useState } from 'react';
import SearchBar from '@/components/SearchBar';
import UserProfile from '@/components/UserProfile';
import { User } from '@/types/User';

const Home: NextPage = () => {
  const [inputValue, setInputValue] = useState('');
  const [user, setUser] = useState<User | null>(null);
  const [isError, setIsError] = useState(false);
  const [theme, setTheme] = useState<'light' | 'dark'>('light');

  const handleSubmit = () => {
    // if username is empty, do nothing
    if (inputValue === '') return;

    void axios
      .get<User>(`https://api.github.com/users/${inputValue}`)
      .then((res) => {
        setUser(res.data);
        setIsError(false);
      })
      .catch((error: AxiosError) => {
        if (error.response?.status === 404) {
          setIsError(true);
        } else {
          console.error(error);
          throw error;
        }
      });
  };

  const handleType = (e: React.ChangeEvent<HTMLInputElement>) => {
    setInputValue(e.target.value);
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.nativeEvent.isComposing || e.key !== 'Enter') return;

    handleSubmit();
  };

  const handleToggleTheme = () => {
    setTheme((prev) => (prev === 'light' ? 'dark' : 'light'));
  };

  useEffect(() => {
    // fetch octocat's information as initial rendering so that user will find an example.
    void axios
      .get<User>('https://api.github.com/users/octocat')
      .then((res) => setUser(res.data));
  }, []);

  useEffect(() => {
    if (theme === 'dark') {
      document.body.classList.add('dark');
    } else {
      document.body.classList.remove('dark');
    }
  }, [theme]);

  return (
    <>
      <Head>
        <title>GitHub User Search App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto flex max-w-xl flex-col justify-center md:max-w-3xl">
        <div className="mb-9 mt-8 flex items-center justify-between">
          <h1 className="text-[26px] text-bold">devfinder</h1>
          <div className="flex gap-x-5">
            <label htmlFor="theme">{theme === 'dark' ? 'LIGHT' : 'DARK'}</label>
            <button id="theme" type="button" onClick={handleToggleTheme}>
              {theme === 'dark' ? (
                <Image
                  src="/assets/icon-sun.svg"
                  alt="sun"
                  width={20}
                  height={20}
                  className="fill-foreground"
                />
              ) : (
                <Image
                  src="/assets/icon-moon.svg"
                  alt="moon"
                  width={20}
                  height={20}
                  className="fill-foreground"
                />
              )}
            </button>
          </div>
        </div>
        <div className="mb-4">
          <SearchBar
            handleSubmit={handleSubmit}
            handleKeyDown={handleKeyDown}
            handleType={handleType}
            isError={isError}
          />
        </div>
        {user && (
          <div className="mb-20">
            <UserProfile user={user} />
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
