import { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import SearchBar from '@/components/SearchBar';
import UserProfile from '@/components/UserProfile';
import { fakeUser } from '@/mocks/fakeData';
import { User } from '@/types/User';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>GitHub User Search App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto flex max-w-xl flex-col justify-center md:max-w-3xl">
        <div className="mb-9 mt-8 flex items-center justify-between">
          {/* TODO: implement dark mode */}
          <h1 className="text-[26px] text-black">divfinder</h1>
          <div className="flex gap-x-5">
            <div className="text-[13px]">DARK</div>
            <Image
              src="/assets/icon-moon.svg"
              alt="moon"
              width={20}
              height={20}
            />
          </div>
        </div>
        <div className="mb-4">
          <SearchBar />
        </div>
        <div className="mb-20">
          <UserProfile user={fakeUser as User} />
        </div>
      </main>
    </>
  );
};

export default Home;
